apiVersion: v1
kind: ServiceAccount
metadata:
  name: whiteboard-api-sa
  namespace: whiteboard-production
  labels:
    app.kubernetes.io/component: backend-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whiteboard-socket-sa
  namespace: whiteboard-production
  labels:
    app.kubernetes.io/component: socket-realtime
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whiteboard-worker-sa
  namespace: whiteboard-production
  labels:
    app.kubernetes.io/component: worker-tasks
