apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: whiteboard-servicemonitor
  namespace: whiteboard-production
  labels:
    app.kubernetes.io/part-of: collaborative-whiteboard
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: collaborative-whiteboard
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
    - port: websocket
      path: /metrics
      interval: 15s
