apiVersion: v1
kind: Secret
metadata:
  name: whiteboard-secrets
  namespace: whiteboard-production
  labels:
    app.kubernetes.io/part-of: collaborative-whiteboard
    app.kubernetes.io/environment: production
type: Opaque
stringData:
  MONGODB_PASSWORD: "ProductionDatabasePasswordSecure123!"
  REDIS_PASSWORD: "ProductionRedisPasswordSecure123!"
  JWT_SECRET: "ProductionSuperSecretJwtKey2026!WithMinimum64BitsLengthForSecurity"
  AWS_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"
  AWS_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
