apiVersion: v1
kind: Service
metadata:
  name: whiteboard-socket
  namespace: whiteboard-production
  labels:
    app: whiteboard-socket
    app.kubernetes.io/component: socket-realtime
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: websocket
  selector:
    app: whiteboard-socket
