apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whiteboard.fullname" . }}-client
  labels:
    app.kubernetes.io/component: client
    {{- include "whiteboard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: client
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: client
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.client.service.port }}
              name: http
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
