apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "whiteboard.fullname" . }}-config
  labels:
    {{- include "whiteboard.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.global.environment | quote }}
  PORT: {{ .Values.api.service.port | quote }}
  SOCKET_PORT: {{ .Values.socket.service.port | quote }}
  WORKER_PORT: {{ .Values.worker.env.PORT | quote }}
  MONGODB_URI: {{ .Values.mongodb.uri | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
